name: spotweb-mysql

services:
  spotweb:
    build: ../
    environment:
      TZ: Europe/Amsterdam
      DB_ENGINE: pdo_mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: spotweb
      DB_USER: spotweb
      DB_PASS: spotweb
      CRON_INTERVAL: '*/1 * * * *'
    ports:
      - '8085:80'
    depends_on:
      - database

  database:
    image: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
