name: spotweb-sqlite

services:
  spotweb:
    build: ../
    environment:
      TZ: Europe/Amsterdam
      DB_ENGINE: pdo_sqlite
      DB_NAME: /data/spotweb.db3
      CRON_INTERVAL: '*/1 * * * *'
    ports:
      - '8085:80'
    volumes:
      - sqlite-data:/data

volumes:
  sqlite-data:
