#!/command/with-contenv bash

if [ "${DB_ENGINE}" = "pdo_sqlite" ]; then
  # Make sure database directory and file exist
  sql_dir=$(dirname "${DB_NAME}")
  mkdir -p "$sql_dir"
  chown abc: "$sql_dir"
  touch "${DB_NAME}"
  chown abc: "${DB_NAME}"
fi

# init/upgrade the db
s6-setuidgid abc php83 /app/bin/upgrade-db.php

# Run query to check if admin has logged in
admin_lastlogin=$(s6-setuidgid abc php83 /app/query.php --get_admin_lastlogin)

if [ $admin_lastlogin -eq 0 ];
then
  echo "Admin has not logged in, set default password (which is: spotweb)"
  s6-setuidgid abc php83 /app/bin/upgrade-db.php --reset-password admin
else
  echo "Admin has already logged in, no need to set default password"
fi
