name: Selenium Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - working-directory: ./selenium
        run: npm install

      - working-directory: ./selenium
        run: docker pull selenium/standalone-chrome

      - working-directory: ./selenium
        run: docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.2.2-20220609

      - working-directory: ./selenium
        run: npm exec -c "mocha test"
        name: Selenium tests
