name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Spotweb with MySQL
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: './docker-compose-mysql.yml'
          up-flags: '--build'
          down-flags: '--volumes --remove-orphans'
          test-command: 'curl http://localhost:8085'

      - name: Test Spotweb with PostgreSQL
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: './docker-compose-postgres.yml'
          up-flags: '--build'
          down-flags: '--volumes --remove-orphans'
          test-command: 'curl http://localhost:8085'

      - name: Test Spotweb with SQLite
        uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: './docker-compose-sqlite.yml'
          up-flags: '--build'
          down-flags: '--volumes --remove-orphans'
          test-command: 'curl http://localhost:8085'
