name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Spotweb with MySQL
        run: docker compose -f ./docker-compose-mysql.yml -p spotwebmysql up --build -d

      - name: Wait for Spotweb to respond with 200 OK
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'http://localhost:8085/'

      - name: Stop Spotweb with MySQL
        run: docker compose -f ./docker-compose-mysql.yml -p spotwebmysql down --volumes --remove-orphans

      # - name: Test Spotweb with PostgreSQL
      #   uses: adambirds/docker-compose-action@v1.3.0
      #   with:
      #     compose-file: './docker-compose-postgres.yml'
      #     compose-flags: '-p spotwebpostgres'
      #     up-flags: '--build'
      #     down-flags: '--volumes --remove-orphans'
      #     test-command: 'curl http://localhost:8086'

      # - name: Test Spotweb with SQLite
      #   uses: adambirds/docker-compose-action@v1.3.0
      #   with:
      #     compose-file: './docker-compose-sqlite.yml'
      #     compose-flags: '-p spotwebsqlite'
      #     up-flags: '--build'
      #     down-flags: '--volumes --remove-orphans'
      #     test-command: 'curl http://localhost:8087'
